inherit_from: https://raw.githubusercontent.com/Bodacious/style-guides/refs/heads/main/.rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: true

Metrics/AbcSize:
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

