name: Ruby

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 3.1.0
          - 3.2.0
          - 3.3.0
          - 3.4.1
          - 3.4.2

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the tests
        run: bundle exec rake test

      - name: Upload coverage to QLTY
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/.resultset.json
