name: Publish

on:
  release:
    types: [published]
permissions: read-all
jobs:
  build:
    name: Publish to RubyGems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
